### ISSUE TITLE
Does not compile in arduino 1.0.6 and 1.6.5

### ISSUE THREAD

**Issue by DeshmukhMalhar** [spake/Arduino-Copier#1]
The errors given by both the IDEs are

BlinkVirus.ino: In function 'void loop()':
BlinkVirus:73: error: 'BYTE' was not declared in this scope

As of Arduino 1.0, the 'BYTE' keyword is no longer supported.
Please use Serial.write() instead.

Copier.ino: In function 'int copier()':
Copier:88: error: 'BYTE' was not declared in this scope

As of Arduino 1.0, the 'BYTE' keyword is no longer supported.
Please use Serial.write() instead.

Copier:104: error: 'BYTE' was not declared in this scope

As of Arduino 1.0, the 'BYTE' keyword is no longer supported.
Please use Serial.write() instead.

**Comment by spake** [comment]
Thanks for pointing this out! I haven't worked on this for over 6 years so I'm probably not going to fix it, but if you do get it compiling in the new IDE, feel free to send me a pull request :)

**Comment by DeshmukhMalhar** [comment]
Surely I'll. OldSteve-Arduino Forum. Is also interested in this. Let's see what happens
